# Typos configuration for panel-skill
# https://github.com/crate-ci/typos

[default.extend-words]
# Technical acronyms
EHR = "EHR"  # Electronic Health Records
AKS = "AKS"  # Azure Kubernetes Service

[files]
extend-exclude = [
    "*.json",
]
